controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

login:
    path: /login
    controller: App\Controller\HomeController::index
    
logout:
    path: /logout
                # where to redirect after logout
                # target: app_any_route